### ISSUE TITLE
Frameworks issue

### ISSUE THREAD

**Issue by wilkinnh** [shaps80/Abracadabra#1]
I ran into build issues when using use_frameworks! in my Podfile. Looks like it's an issue with doing something like #import "SPXCommonDefines.h". I was able to change this to #import <SPXDefines/SPXDefinesCommon.h> and it worked. I think there might be a better solution that involves using @import, but I'm not 100% of that.

**Comment by shaps80** [comment]
I just started using a better tool for tracking all my issues on GitHub and have only just been made aware of this one. Apologies for never getting back to you. Hope you solved the problem anyway?

**Comment by shaps80** [comment]
FYI: I'm sure you're no longer using this -- but in any case. I am unable to update the Pod for this since a lot has changed since this was released and its dependencies would also require updating. However the project does run so if you DO need this project still -- I now recommend dragging the files into your own project manually.

I will NO LONGER be providing any support for this library.

Thank you for using my code.
